name: Update Rainfall and Deploy Hexo

on:
  schedule:
    - cron: '55 * * * *'  # 每整點觸發
  workflow_dispatch:  # 手動觸發

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests pyyaml

    - name: Run Python script to update water volume
      run: |
        python scraper.py  # 替換成你的 Python 腳本名稱

    # 提交更新
    - name: Configure git
      run: |
        git config --global user.name "Your GitHub Username"
        git config --global user.email "your-email@example.com"

    - name: Commit and push changes
      run: |
        git add index.html  # 你希望提交的文件
        git commit -m "Update water volume in index.html"
        git push origin main  # 提交回 main 分支

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
