name: Update Rainfall and Deploy Hexo

on:
  schedule:
    - cron: '55 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # 給 GITHUB_TOKEN 寫入權限

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests pyyaml beautifulsoup4

    - name: Run Python script to update water volume
      run: |
        python scraper.py

    - name: Configure git
      run: |
        git config --global user.name "CJ10110425"
        git config --global user.email "ze0966747312@gmail.com"

    - name: Commit and push changes
      run: |
        git add index.html
        git commit -m "Update water volume in index.html"
        git push origin main

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
