name: Update Rainfall chart and Deploy Hexo

on:
  schedule:
  - cron: '0 23 * * *'  # 每天 23:00 運行
  workflow_dispatch:

permissions:
  contents: write  # 給 GITHUB_TOKEN 寫入權限

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests pyyaml beautifulsoup4

    - name: Check if today is the update day (every 3 days)
      run: |
        today=$(date +%s)
        start_date=$(date -d '2024-01-01' +%s)  # 設定一個開始日期
        days_since_start=$(( (today - start_date) / 86400 ))
        if [ $(( days_since_start % 3 )) -eq 0 ]; then
          echo "Today is the update day."
        else
          echo "Today is not the update day, skipping."
          exit 1
      continue-on-error: true

    - name: Run Python script to update water volume
      run: |
        python rain_fall.py

    - name: Configure git
      run: |
        git config --global user.name "CJ10110425"
        git config --global user.email "ze0966747312@gmail.com"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update Rainfall chart in index.html"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
